### ISSUE TITLE
[Suggestion] Glass stairs and slabs

### ISSUE THREAD

**Issue by Matthysse** [Eltrut-Co/Lepton#21]
Hello!
It would be awesome if you could add glass stairs and slabs to make roof windows or more modern-style builds!

**Comment by EltrutLikes** [comment]
Hey!
Unfortunately, this is not something I plan to implement, since it would require a lot of work to code and get rendering correctly (for example, the glass doors and trapdoors in UA still don't render correctly due to modding bugginess). If you have any further suggestions, however, feel free to post them in my Discord!
