### ISSUE TITLE
missing mods support

### ISSUE THREAD

**Issue by 0Navis0** [Eltrut-Co/Lepton#26]
Here are some mods which could be supported by Lepton.
- Biomes O Plenty
- Create
- Tinkers Construct
- Ceramics
- Botania
- Astral Sorcery

I made a detailed list for woodcutter and kiln which could help you. https://github.com/svenhjol/Covalent/issues/6

**Comment by EltrutLikes** [comment]
As of now, I am not currently planning on supporting mods beyond Abnormals and Aurora since a) I have to draw the boundary somewhere b) that's mostly what I play with and c) this type of mod compat really should be done on the other mods' ends instead of mine so I don't want to make this messier than it already is. You're welcome to make a compat mod that adds these tho, it would just be too much for me to maintain unfortunately.

**Comment by 0Navis0** [comment]
Eh ok I understand, what you currently do is already awesome.
