### ISSUE TITLE
[1.16.5] Sandstone Tag Issue

### ISSUE THREAD

**Issue by HenryMaxler** [Eltrut-Co/Lepton#34]
Hello,

I was playing and I noticed a missing texture shows up in JEI when looking at Immersive Engineering Coke Brick recipe that uses sandstone.  I think it might be a problem in the lepton-1.16.5-1.3.2.jar\data\forge\tags\blocks\ and lepton-1.16.5-1.3.2.jar\data\forge\tags\items\
sandstone files.  These files show 

{
  "replace": false,
  "values": [
    "lepton:cracked_sandstone",
	"lepton:cracked_red_sandstone",
	_**"lepton:cracked_arid_sandstone",
	"lepton:cracked_red_arid_sandstone",
	"lepton:cracked_glowdust_sandstone"**_
  ]
}

Where the items in bold don't seem to exist, they show up as missing textures.  Not sure if it is possible for me to fix this myself with CraftTweaker.

**Comment by EltrutLikes** [comment]
This happens when you use Lepton without Infernal Expansion. These blocks shouldn't show up in the creative inventory or anywhere else since it pulls the texture from Infernal Expansion so unless that is happening this is something I cannot fix.

(Forge recommends as of 1.13 to register every block, regardless of whether or not all of the supporting mods are installed. This is for safety reasons so this is not something I can fix.)

**Comment by HenryMaxler** [comment]
No problem, thanks for the reply.  Was able to fix it with a mini texture pack.
